### PR TITLE
Fixed serverside crash and Fixed GuiLinker

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Sorry my first works with git. now you have the guilinker fix here to.

**Review by Doc-1 — APPROVED** [review]
Fixed serverside crash

**Review by Doc-1 — COMMENTED** [review]
It is designed for the position relative to the structure. Not an exact position.

**Comment by Doc-1** [comment]
Added option that lets you use either relative or absolute coordinates for the Remote Activator. Also GuiLinker is now renamed to Remote Activator.

**Comment by ghost** [comment]
Thanks for your work!

**Pull request merged**
